NovoControleProjetos/Models/Iniciativa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NovoControleProjetos.Models
{
    public class Iniciativa
    {
        public int Id_Iniciativa { get; set; }
        public string nome_iniciativa { get; set; }
        public int? num_iniciativa { get; set; }
        public int? id_departamento { get; set; }
        public DateTime? data_aprovacao { get; set; }
        public DateTime? data_piloto { get; set; }
        public DateTime? data_plenouso { get; set; }
        public DateTime? data_comunicacao { get; set; }
        public int? id_esteira { get; set; }
        public int? id_farol { get; set; }
        public string cor_farol { get; set; }
        public string ds_farol { get; set; }
        public int? id_etapa { get; set; }
        public string CPF { get; set; }
        public int? id_mega { get; set; }
        public string TF_versao_agencia { get; set; }
        public string TF_versao_PA { get; set; }
        public string responsavel_neg { get; set; }
        public string responsavel_DS { get; set; }
        public string resumo_iniciativa { get; set; }
        public bool? usabilidade { get; set; }
        public string beneficio_iniciativa { get; set; }
        public Orcamento orcamento { get; set; }
        public Ceti ceti { get; set; }
        public List<int> idsOrigens { get; set; }
        public int? id_orcamento { get; set; }
        //public decimal VPL { get; set; }
        public Jornada jornada { get; set; }
        public int id_jornada { get; set; }
        public int? id_ceti { get; set; }
        public int? id_replanejamento { get; set; }
        public int? id_visita { get; set; }
        public Replanejamento replanejamento { get; set; }
        public Visita visita { get; set; }
        //public Farol farol  { get  { return new Farol(); } set {  }
          
        //}
        public Farol farol { get; set; }

    }
}

NovoControleProjetos/Controllers/CanalController.cs
using NovoControleProjetos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NovoControleProjetos.Controllers
{
    public class CanalController : Controller
    {
        DAL.Canal_DAL canal_DAL = new DAL.Canal_DAL();
        RelacionamentosController relacionamentosController = new RelacionamentosController();
        // GET: Canal
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult _ListaCanais(int? id_canal, int? id_iniciativa)
        {

            List<Checkados> checkados = new List<Checkados>();
            if (id_iniciativa != null)
            {
                checkados = relacionamentosController.BuscaCheckados(id_iniciativa, "canais", "id_projeto", "id_canal", "dt_canal", null);

                ViewBag.Checkadas = checkados;
            }

            var canais = canal_DAL.ListaCanais().Where(x => x.Ativo == true).OrderBy(x => x.Ds_Canal);      
                       
            return View(canais);
        }
    }
}

NovoControleProjetos/Controllers/IniciativaController.cs
using Newtonsoft.Json;
using NovoControleProjetos.DAL;
using NovoControleProjetos.Models;
using NovoControleProjetos.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace NovoControleProjetos.Controllers
{
    public class IniciativaController : Controller
    {
        DAL.Iniciativa_DAL iniciativa_DAL = new DAL.Iniciativa_DAL();
        OrcamentoController orcamentoController = new OrcamentoController();
        RelacionamentosController relacionamentosController = new RelacionamentosController();
        CetiController cetiController = new CetiController();
        JornadaController jornadaController = new JornadaController();
        ReplanejamentoController replanejamentoController = new ReplanejamentoController();
        FarolController farolController = new FarolController();
        VisitaController visitaController = new VisitaController();
        Mvp_DAL Mvp_DAL = new Mvp_DAL();
        Projeto_DAL Projeto_DAL = new Projeto_DAL();


        // GET: Iniciativa
        public ActionResult Index(bool teste)
        {
            ViewBag.Sucesso = teste;
            return View();
        }

        public ActionResult Create(int id)
        {
            Iniciativa projeto = iniciativa_DAL.GetIniciativa(id);
            Orcamento orcamento = new Orcamento();
            projeto.orcamento = orcamento;

            return View(projeto);
        }

        [HttpPost]
        public ActionResult Create(Iniciativa iniciativa, Orcamento orcamento, List<Origem> origens, List<Etapa> etapas, List<Vertical> verticais,
                                  List<Canal> canais, Visita visita, Jornada jornada, Ceti ceti, Replanejamento replanejamento, Farol farol)
        {

            try
            {

                if (verticais != null)
                {
                    bool Ok = relacionamentosController.RelacionamentosProjetoComListas(iniciativa.Id_Iniciativa, verticais.Select(x => x.Id_Vertical).ToList(), "Verticais", null, null);
                    if (!Ok)
                    {
                        return new HttpStatusCodeResult(404);
                    }
                }
                else
                {
                    bool Ok = relacionamentosController.DeletaRelacionamento(iniciativa.Id_Iniciativa, "projeto_verticais", "id_projeto");
                    if (!Ok)
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }

                if (origens != null)
                {
                    bool Ok = relacionamentosController.RelacionamentosProjetoComListas(iniciativa.Id_Iniciativa, origens.Select(x => x.Id_Origem).ToList(), "Origens", null, null);
                    if (!Ok)
                    {
                        return new HttpStatusCodeResult(404);
                    }
                }
                else
                {
                    bool Ok = relacionamentosController.DeletaRelacionamento(iniciativa.Id_Iniciativa, "projeto_origens", "id_projeto");
                    if (!Ok)
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }

                if (etapas != null)
                {
                    bool Ok = relacionamentosController.RelacionamentosProjetoComListas(iniciativa.Id_Iniciativa, null, "Etapas", etapas, null);
                    if (!Ok)
                    {
                        return new HttpStatusCodeResult(404);
                    }
                }
                else
                {
                    bool Ok = relacionamentosController.DeletaRelacionamento(iniciativa.Id_Iniciativa, "projeto_etapas", "id_projeto");
                    if (!Ok)
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }


                if (canais != null)
                {
                    bool Ok = relacionamentosController.RelacionamentosProjetoComListas(iniciativa.Id_Iniciativa, canais.Select(x => x.Id_Canal).ToList(), "Canais", null, canais);
                    if (!Ok)
                    {
                        return new HttpStatusCodeResult(404);
                    }
                }
                else
                {
                    bool Ok = relacionamentosController.DeletaRelacionamento(iniciativa.Id_Iniciativa, "projeto_canais", "id_projeto");
                    if (!Ok)
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }

                if (orcamento != null)
                {

                    orcamentoController.InsereOrcamento(orcamento, iniciativa.Id_Iniciativa);
                }

                if (jornada != null)
                {
                    iniciativa.id_jornada = jornadaController.InsereJornada(jornada, iniciativa.Id_Iniciativa);
                }


                if (ceti.Data_Ceti != null || ceti.Total_Aprovado_Ceti != null || iniciativa.id_ceti != null)
                {
                    Ceti objCeti = new Ceti();
                    string oper = null;
                    if (iniciativa.id_ceti != null)
                    {
                        objCeti = cetiController.BuscaCeti(null, iniciativa.id_ceti);
                        oper = ceti.Data_Ceti != objCeti.Data_Ceti ? "I" : "U";
                    }

                    var id_ceti = cetiController.InsereCeti(ceti, iniciativa.Id_Iniciativa, iniciativa.id_ceti, oper ?? "I");

                    iniciativa.id_ceti = id_ceti;
                }

                if (replanejamento.data_replanejamento != null || replanejamento.motivo_replanejamento != null)
                {

                    Replanejamento objReplan = new Replanejamento();
                    string oper = null;
                    if (iniciativa.id_replanejamento != null)
                    {
                        objReplan = replanejamentoController.BuscaReplanejamento(null, iniciativa.id_replanejamento);
                        oper = replanejamento.data_replanejamento != objReplan.data_replanejamento ? "I" : "U";
                    }

                    iniciativa.id_replanejamento = replanejamentoController.InsereReplanejamento(replanejamento, iniciativa.Id_Iniciativa, iniciativa.id_replanejamento, oper ?? "I");

                }


                if (farol.Comentario_Farol != null)
                {
                    string oper = null;
                    Farol _farol = new Farol();

                    if (iniciativa.id_farol != null)
                    {
                        var objfarol = farolController.BuscaFarol(iniciativa.Id_Iniciativa, iniciativa.id_farol);
                        oper = objfarol.Id_Comentario_Farol != null ? "U" : "I";
                    }

                    farolController.InsereComentarioFarol(farol, iniciativa.Id_Iniciativa, iniciativa.id_farol, farol.Id_Comentario_Farol != null ? farol.Id_Comentario_Farol : null, oper);
                }

                if (visita.Data_Visita != null || visita.Cod_Agencia != null)
                {
                    string oper = null;
                    Visita _visita = new Visita();

                    if (iniciativa.id_visita != null)
                    {
                        var objVisita = visitaController.BuscaVisita(iniciativa.id_visita, null);
                        oper = objVisita.Data_Visita != visita.Data_Visita || objVisita.Cod_Agencia != visita.Cod_Agencia ? "I" : "U";
                    }

                    iniciativa.id_visita = visitaController.InsereVisita(visita, iniciativa.Id_Iniciativa, iniciativa.id_visita, oper ?? "I");

                }

                //iniciativa.id_orcamento = idOrcamento;
                //relacionamentosController.RelacionamentoOrcamentoProjeto(iniciativa.Id_Iniciativa, idOrcamento);          

                iniciativa_DAL.UpdateIniciativa(iniciativa);

                return RedirectToAction("Index", "Home", true);
            }
            catch (Exception ex)
            {
                throw;
            }



        }
        [HttpPost]
        public JsonResult InsertMVP(string Mvp)
        {
            try
            {
                var mvpConvert = JsonConvert.DeserializeObject<List<Mvp>>(Mvp);
                Mvp_DAL.InsereMvpNoBanco(mvpConvert);
                ViewBag.Sucesso = true;
            }
            catch (Exception)
            {
                ViewBag.Sucesso = false;
            }

            return Json("Sucesso", JsonRequestBehavior.AllowGet);

        }

        public ActionResult BuscaIniciativa(int? id_iniciativa)
        {
            Iniciativa iniciativa = new Iniciativa();
            iniciativa = iniciativa_DAL.Buscainiciativa(id_iniciativa);

            return View(iniciativa);
        }

        public ActionResult _InsertIniciativa()
        {
            return PartialView();
        }

        [HttpPost]
        public JsonResult _InsertIniciativa(string nome)
        {
            var id = iniciativa_DAL.RetornaIdIniciativa(nome);
            return Json(id, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditaIniciativa(int? id)
        {

            Iniciativa iniciativa = iniciativa_DAL.Buscainiciativa(id);

            return View(iniciativa);
        }


        /// <summary>
        /// Método para pegar os dados mvp e tratalos caso a data venha nula
        /// </summary>
        /// <param name="id_iniciativa"></param>
        /// <param name="replanejamento"></param>
        /// <returns></returns>
        public ActionResult _DetalhesIniciativa(int? id_iniciativa, Replanejamento replanejamento)
        {

            ViewBag.id_Iniciativa = id_iniciativa;

NovoControleProjetos/Views/Iniciativa/ErroAmigavel.cshtml
@{ 

    Layout = null;
}




<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Erro</title>
</head>
<body>
    <hgroup>
        <h1>Erro.</h1>
        <h2>Ocorreu um erro ao processar sua solicitação.</h2>

        <h3>Tente limpar o cache, sair e entrar novamente e realize uma nova tentaiva.</h3>
        <h2>Caso persista, por favor contatar o responsável pela aplicação.</h2>
        <h2> Lembre-se de informar qual foi a ação realizada antes de acontecer o erro.</h2>

    </hgroup>
</body>
</html>

NovoControleProjetos/Views/Iniciativa/ListaProjetos.cshtml
@model IEnumerable<NovoControleProjetos.Models.ViewModel.ListaDeProjetosModelView>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            @using (Html.BeginForm("PesquisaPorDepartamento", "Iniciativa", FormMethod.Post, new { @class = "navbar-form navbar-left", role = "form" }))
            {
                <div class="navbar-form navbar-left"></div>
                <div class="form-group">
                    <div class="form-group">
                        <label for="nomeProjeto">Nome do departamento</label>
                        <input type="text" name="Nome" class="form-control" value="@ViewBag.nomeDepartamento" />
                    </div>
                </div>
                <button type="submit" class="btn btn-info">Buscar</button>
            }

        </div>
    </nav>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title"><strong>Total de Projetos: </strong>@Model.Count(obj => obj.IdIniciativa > 0)</h3>
        </div>
    </div>
    <div class=" panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdIniciativa)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NomeIniciativa)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.NomeDepartamento)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DtAprovacao)
                    </th>
                    <th></th>
                </tr>
            </thead>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdIniciativa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeIniciativa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeDepartamento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DtAprovacao)
                    </td>
                    <td>
                        <div class="btn-group">
                            @Html.ActionLink("Editar", "EditaIniciativa", "Iniciativa", new { id = item.IdIniciativa }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Detalhes", "DetalheProjeto", "Iniciativa", new { id = item.IdIniciativa }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-info disabled" })
                        </div>
                    </td>
                </tr>
            }

        </table>
    </div>
</body>

NovoControleProjetos/Views/Iniciativa/_DetalhesIniciativa.cshtml
@model NovoControleProjetos.Models.Replanejamento

@{
    Layout = null;
    var id = ViewBag.id_Iniciativa;

    var dtReplanejamento = Model.data_replanejamento != null ? Model.data_replanejamento.Value.ToShortDateString() : null;
}

<head>

    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">*@
    <style>
        label {
            font-size: 15px;
            font-weight: normal;
        }

        input {
            font-size: 14px;
            font-family: 'Calisto MT';
        }
    </style>
</head>
<body>
    <div class="form-group col-md-5" style=" border: 1px solid #ccc;  width: 650px;  margin: 5px;">

        <div class="row" style="padding-top:15px;">
            <div class="col-md-4" style="width: 152.75px; padding-left: 0px;">
                <label for="form-parcial-etapa" style=" padding-left: 15px; color:brown"> Etapas:</label>
            </div>
            <div class="col-md-3">
                <label for="form-parcial-etapa-inicio" style=" padding-left: 15px; color:brown;  margin-left:90px"> Início:</label>
            </div>
            <div class="col-md-3">
                <label for="form-parcial-etapa-fim" style=" padding-left: 15px; color:brown; margin-left:90px"> Fim:</label>
            </div>

        </div>

        @{Html.RenderAction("_ListaEtapas", "Etapa", new { @id_iniciativa = id });}
        <br />

    </div>

    <div class="col-md-5" style=" border: 1px solid #ccc;  margin-left: 11px; margin-top: 5px; border-image: none ">

        <input hidden id="id_replanejamento" value="@Model.id_replanejamento" />

        <div class="row" style="padding: 15px">
            <label style="display:inline-block" for="data-replanejamento">Replanejamento</label>
            <input style="display:inline-block" type="text" id="data-replanejamento" value="@dtReplanejamento" name="data-replanejamento" onkeypress="mascara(this, mdata);" size="14" maxlength="10" class="form-control" placeholder="DD/MM/AAAA" />
        </div>

        <div class="row" style="padding: 15px">
            <label>Motivo:</label>
            @*<textarea id="motivo-replanejamento" value="@Model.motivo_replanejamento" rows="6" class="form-control" style="min-width: 90%;"></textarea>*@
            @Html.TextAreaFor(model => model.motivo_replanejamento, new { @id = "motivo-replanejamento", @class = "form-control", @rows = "6", @style = " min-width: 90%;" })
        </div>


    </div>

    <div class="row" style="margin-left:0px;">

        <div class="form-group col-md-4" style="padding-right:0px; padding-left:0px; padding-top: 15px; padding-bottom: 15px; margin-left: 15px; margin-top: 15px; border: 1px solid #ccc;  width: 650px; margin: 5px">

            <div>
                <label for="form-parcial-etapa" style=" color: brown; padding-bottom: 8px; padding-left: 15px;"> Canais:</label>
            </div>

            @{Html.RenderAction("_ListaCanais", "Canal");}

        </div>

        <div class="form-group col-md-5" style="  margin-left: 15px; border: 1px solid #ccc;  margin-left:5px; margin-top: 10px ">

            <div id="DivMVP" name="DivMvp" class="row" style="padding: 15px; padding-bottom:5px; padding-top:11px;">
                <div>
                    <label style=" color: brown; padding-right: 365px;">MVP:</label><img src="~/Imagens/download.png" style="cursor:pointer" onclick="duplicarCampo()">

                    <img src="~/Imagens/red-subtract-icon-png-13.png" style="cursor:pointer" id="excluiCampo" onclick="removerCampos()">


                </div>
                @if (ViewBag.acao == "criar")
                {
                    <div class="filho">
                        <input hidden name="id-mvp[]" class="active" id="id-mvp" value="" />
                        <input class="active" id="mvp-iniciativa" hidden name="id-iniciativa[]" value="@ViewBag.id_Iniciativa" />
                        <div class="col-md-6" style="padding-left:0;">
                            <label for="mvp-nome">Nome</label>
                            <input type="text" id="mvp-nome" name="mvp-nome[]" class="form-control" value="" />
                        </div>

                        <div class="col-md-6">
                            <label for="mvp-entrega">Entrega</label>
                            <input type="text" id="mvp-entrega" name="mvp-entrega[]" value="" onkeypress="mascara(this, mdata);" size="14" maxlength="10" class="form-control" placeholder="DD/MM/AAAA" />
                        </div>
                    </div>
                }
                else
                {
                    int contador = 0;
                    foreach (var item in ViewBag.MVP)
                    {
                        <div class="filho">
                            <input hidden name="id-mvp[]" class="active" id="id-mvp" value="@item.Id_Mvp" />
                            <input class="active" id="mvp-iniciativa" hidden name="id-iniciativa[]" value="@item.Id_Iniciativa" />
                            <div class="col-md-6" style="padding-left:0;">
                                <label for="mvp-nome">Nome</label>
                                <input type="text" id="mvp-nome" name="mvp-nome[]" class="form-control" value="@item.Nome_Mvp" />
                            </div>

                            <div class="col-md-6">
                                <label for="mvp-entrega">Entrega</label>
                                <input type="text" id="mvp-entrega" name="mvp-entrega[]" value="@ViewBag.dtConvertido[contador]" onkeypress="mascara(this, mdata);" size="14" maxlength="10" class="form-control" placeholder="DD/MM/AAAA" />
                            </div>
                        </div>
                        contador++;
                    }
                }
                <div id="destino"></div>
            </div>

            @*<div class="row" style="padding: 15px; padding-top:2px; padding-bottom:5px;">
                    <input hidden id="id-mvp1" value="@ViewBag.Id_Mvp1" />
                    <div class="col-md-6" style="padding-left:0;">
                        <label for="mvp-nome">Nome</label>
                        <input type="text" id="mvp-nome-um" name="mvp-nome" value="@ViewBag.NomeMvp1" class="form-control" />
                    </div>

                    <div class="col-md-6">
                        <label for="mvp-entrega">Entrega</label>
                        <input type="text" id="mvp-entrega-um" name="mvp-entrega" value="@ViewBag.DataMvp1" onkeypress="mascara(this, mdata);" size="14" maxlength="10" class="form-control" placeholder="DD/MM/AAAA" />
                    </div>

                </div>

                <div class="row" style="padding: 15px; padding-top:2px; padding-bottom:5px;">
                    <input hidden id="id-mvp2" value="@ViewBag.Id_Mvp2" />
                    <div class="col-md-6" style="padding-left:0;">
                        <label for="mvp-nome">Nome</label>
                        <input type="text" id="mvp-nome-dois" name="mvp-nome" class="form-control" value="@ViewBag.NomeMvp2" />
                    </div>

                <div class="col-md-6">
                    <label for="mvp-entrega">Entrega</label>
                    <input type="text" id="mvp-entrega-dois" name="mvp-entrega" value="@ViewBag.DataMvp2" onkeypress="mascara(this, mdata);" size="14" maxlength="10" class="form-control" placeholder="DD/MM/AAAA" />
                </div>

                </div>*@

        </div>

    </div>




    <script type="text/javascript">


        //window.onload = ocultaMenos;

        ///Função para duplicar os campos de MVP
        function duplicarCampo() {

            $("#destino").before('<div class = "form-group has-success" style="padding-right: 13px; padding-left: 18px;"> '+ " " + ' <input hidden name="id-mvp[]" class="active" id="id-mvp" />' + " " +
                '<input class="active" id="mvp-iniciativa" hidden name="id-iniciativa[]" value = "@ViewBag.id_Iniciativa" />' + " " +
                '<div class="col-md-6" style="padding-left:0;">' + " " +
                '<label for="mvp-nome">Nome</label>' + " " +
                '<input type="text" id="mvp-nome" name="mvp-nome[]" class="form-control" />' + " " +
                '</div>' + " " + ' <div class="col-md-6">' + " " + '<label for="mvp-entrega">Entrega</label>' + " " +
                '<input type="text" id="mvp-entrega" name="mvp-entrega[]" onkeypress="mascara(this, mdata);" size="14" maxlength="10" class="form-control" placeholder="DD/MM/AAAA" />' + " " +
                '</div>' + " " + '</div>')

        }

        //    var qtdInputs = document.getElementsByName('mvp-nome[]')
        //    document.getElementById('excluiCampo').style.display = 'inline';
        //    var clone = document.getElementById('origem').cloneNode(true)
        //    var destino = document.getElementById('destino');

        //    destino.appendChild(clone);

        //    for (var i = 0; i < qtdInputs.length; i++) {
        //        clone.getElementsByTagName('input').value = "";
        //    }
        //    //clone.getElementsByTagName('input')[1].id = "id-mvp" + contador;
        //    //clone.getElementsByTagName('input')[2].id = "mvp-iniciativa" + contador;
        //    //clone.getElementsByTagName('input')[3].id = "mvp-nome" + contador;
        //    //clone.getElementsByTagName('input')[3].value = "";
        //    //clone.getElementsByTagName('input')[4].id = "mvp-entrega" + contador;
        //    //clone.getElementsByTagName('input')[4].value = "";

        //}



        //Função para excluir campos do MVP
            function removerCampos() {

                if (document.getElementsByName('mvp-nome[]').length != 1) {

                    let verifica = $("#destino").prev();

                    if (verifica.hasClass("form-group has-success")) {
                        $("#destino").prev().remove();
                    }
                    else {
                        alert("Você só pode excluir linhas na qual foram inclusas")
                    }
                }

            };

        @*$(document).ready(function () {
            PegarDadosMvp();
        });

        function PegarDadosMvp() {

            $.ajax({
                type: "POST",
                cache: false,
                data: @ViewBag.id_Iniciativa,
                url: "/PopulaMvps/Iniciativa",
                success: function (data) {
                    UpdateIniciativa();
                },
                error: function (data) {

                    window.location.href = "/Iniciativa/ErroAmigavel";
                }

            });
        }*@

            @*$.ajax(
                {
                    type: "POST",
                    url: "@Url.Action("PopulaMvps", "Iniciativa")",
                    data: @ViewBag.id_Iniciativa,
                    success: function (data) {
                        var PopulaMvp = $("#PopulaMvps");
                        $.each(data, function (index, item) {

                            var div = ("<div></div>");
                            div.html($("<input hidden name='id-mvp[]' class='active' id='id-mvp1' value = " + item.Id_Mvp + " />")
                                + " " + ("<input class='active' id='mvp-iniciativa1' hidden name='id-iniciativa[]' value= " + item.Id_Iniciativa + "/>")
                                + " " + ("<div class='col-md-6' style='padding-left: 0;'>")
                                + " " + ("<label for='mvp-nome'>Nome</label>")
                                + " " + ("<input type='text' id='mvp-nome1' name='mvp-nome[]' class='form-control' value = " + item.Nome_Mvp + " />")
                                + " " + ("</div>")
                                + " " + ("<div class='col-md-6'>")
                                + " " + ("<label for='mvp-entrega'>Entrega</label>")
                                + " " + ("<input type='text' id='mvp-entrega1' name='mvp - entrega[]' onkeypress='mascara(this, mdata); ' size='14' maxlength='10' class='form-control' placeholder='DD / MM / AAAA' value = " + item.Dt_Mvp + " />")
                                + " " + ("</div>"));
                });
                    },
                }
            )*@

            @*$.get('@Url.Action("PopulaMvps", "Iniciativa")', function (data) {
                var PopulaMvp = $("#PopulaMvp");
                $.each(data, function (index, item) {

                    var div = ("<div></div>");
                    div.html($("<input hidden name='id-mvp[]' class='active' id='id-mvp1' value = " + item.Id_Mvp + " />")
                        + " " + ("<input class='active' id='mvp-iniciativa1' hidden name='id-iniciativa[]' value= " + item.Id_Iniciativa + "/>")
                        + " " + ("<div class='col-md-6' style='padding-left: 0;'>")
                        + " " + ("<label for='mvp-nome'>Nome</label>")
                        + " " + ("<input type='text' id='mvp-nome1' name='mvp-nome[]' class='form-control' value = " + item.Nome_Mvp + " />")
                        + " " + ("</div>")
                        + " " + ("<div class='col-md-6'>")
                        + " " + ("<label for='mvp-entrega'>Entrega</label>")
                        + " " + ("<input type='text' id='mvp-entrega1' name='mvp - entrega[]' onkeypress='mascara(this, mdata); ' size='14' maxlength='10' class='form-control' placeholder='DD / MM / AAAA' value = " + item.Dt_Mvp + " />")
                        + " " + ("</div>"));

                })
            })*@
        //}

    </script>
</body>